# Generated by Django 5.2.15 on 2026-06-16 03:07

import common.labeled_enum
import django.db.models.deletion
import django.db.models.functions.text
import organization.enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="organization.organization",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.CreateModel(
            name="OrganizationInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "organization_role",
                    common.labeled_enum.LabeledEnumField(
                        default="member",
                        enum_class=organization.enums.OrganizationRole,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Role",
                    ),
                ),
                (
                    "status",
                    common.labeled_enum.LabeledEnumField(
                        default="waiting",
                        enum_class=organization.enums.OrganizationInvitationStatus,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_organization_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invited By",
                    ),
                ),
                (
                    "invited_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_organization_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invited User",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="organization.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Invitation",
                "verbose_name_plural": "Organization Invitations",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("email_address__isnull", False),
                            ("invited_user__isnull", False),
                            _connector="OR",
                        ),
                        name="invitation_has_email_or_user",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email_address"),
                        models.F("organization"),
                        condition=models.Q(
                            ("email_address__isnull", False), ("status", "waiting")
                        ),
                        name="unique_pending_invitation_per_org_email",
                    ),
                    models.UniqueConstraint(
                        models.F("invited_user"),
                        models.F("organization"),
                        condition=models.Q(
                            ("invited_user__isnull", False), ("status", "waiting")
                        ),
                        name="unique_pending_invitation_per_org_user",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "organization_role",
                    common.labeled_enum.LabeledEnumField(
                        default="member",
                        enum_class=organization.enums.OrganizationRole,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Role",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="organization.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_members",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Member",
                "verbose_name_plural": "Organization Members",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "user"),
                        name="unique_organization_member",
                    )
                ],
            },
        ),
    ]
