import os
import re
import time


def generate_unique_filename( filename : str ):
    original_name, extension = os.path.splitext( filename )
    timestamp = int( time.time() )
    unique_name = f'{original_name}-{timestamp}{extension}'
    return unique_name


def derive_new_unique_filename( filename : str ):
    """
    Generate a new unique filename, replacing any existing timestamp suffix
    rather than appending. If the filename was previously generated by
    generate_unique_filename (ending in -{digits}), the old timestamp is
    replaced with a new one. Otherwise behaves like generate_unique_filename.
    """
    original_name, extension = os.path.splitext( filename )
    original_name = re.sub( r'-\d+$', '', original_name )
    timestamp = int( time.time() )
    return f'{original_name}-{timestamp}{extension}'
